INFO - 2024-05-28 21:23:09 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"ss","estado":"pendiente"}
INFO - 2024-05-28 21:23:09 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"ss","estado":"pendiente"}
CRITICAL - 2024-05-28 21:30:48 --> ErrorException: Undefined property: stdClass::$id_tarea
[Method: POST, Route: tareas/delete]
in APPPATH/Controllers/TareasController.php on line 65.
 1 APPPATH/Controllers/TareasController.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id_tarea', '/Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php', 65)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->delete()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-28 21:30:55 --> Datos recibidos para guardar tarea: {"nombre_tarea":"hvhvhv","descripcion_tarea":"ss","estado":"0"}
INFO - 2024-05-28 21:30:55 --> Datos recibidos para guardar tarea: {"nombre_tarea":"hvhvhv","descripcion_tarea":"ss","estado":"0"}
INFO - 2024-05-28 21:31:02 --> ID de la tarea recibido para eliminar: 3
INFO - 2024-05-28 21:31:02 --> ID de la tarea recibido para eliminar: 3
INFO - 2024-05-28 21:31:02 --> Tarea eliminada correctamente
INFO - 2024-05-28 21:31:08 --> ID de la tarea recibido para eliminar: 2
INFO - 2024-05-28 21:31:08 --> ID de la tarea recibido para eliminar: 2
INFO - 2024-05-28 21:31:08 --> Tarea eliminada correctamente
INFO - 2024-05-28 21:31:38 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":null}
INFO - 2024-05-28 21:31:38 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":null}
ERROR - 2024-05-28 21:31:38 --> mysqli_sql_exception: Column 'estado' cannot be null in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ta...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ta...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ta...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ta...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 /Users/unaibueno/Desktop/Mond/app/Models/TareasModel.php(29): CodeIgniter\Model->insert(Array)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->save()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-28 21:31:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'estado' cannot be null
[Method: POST, Route: tareas/save]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 6 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 21:31:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'estado' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:38\', \'2024-05-28 21:31:38\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:38\', \'2024-05-28 21:31:38\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 8 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 21:31:38 --> [Caused by] mysqli_sql_exception: Column 'estado' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:38\', \'2024-05-28 21:31:38\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:38\', \'2024-05-28 21:31:38\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:38\', \'2024-05-28 21:31:38\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 9 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-28 21:31:40 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":null}
INFO - 2024-05-28 21:31:40 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":null}
ERROR - 2024-05-28 21:31:41 --> mysqli_sql_exception: Column 'estado' cannot be null in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ta...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ta...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ta...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ta...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 /Users/unaibueno/Desktop/Mond/app/Models/TareasModel.php(29): CodeIgniter\Model->insert(Array)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->save()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-28 21:31:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'estado' cannot be null
[Method: POST, Route: tareas/save]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 6 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 21:31:41 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'estado' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:40\', \'2024-05-28 21:31:40\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:40\', \'2024-05-28 21:31:40\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 8 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 21:31:41 --> [Caused by] mysqli_sql_exception: Column 'estado' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:40\', \'2024-05-28 21:31:40\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:40\', \'2024-05-28 21:31:40\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (\'ss\', \'sss\', NULL, \'2024-05-28 21:31:40\', \'2024-05-28 21:31:40\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tareas` (`nombre_tarea`, `descripcion_tarea`, `estado`, `created_at`, `updated_at`) VALUES (:nombre_tarea:, :descripcion_tarea:, :estado:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Models/TareasModel.php(29): CodeIgniter\Model->insert([...])
 9 APPPATH/Controllers/TareasController.php(36): App\Models\TareasModel->saveTask([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->save()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-28 21:31:52 --> Datos recibidos para guardar tarea: {"nombre_tarea":"s","descripcion_tarea":"s","estado":"0"}
INFO - 2024-05-28 21:31:52 --> Datos recibidos para guardar tarea: {"nombre_tarea":"s","descripcion_tarea":"s","estado":"0"}
INFO - 2024-05-28 21:32:36 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sw","descripcion_tarea":"sss","estado":"1"}
INFO - 2024-05-28 21:32:36 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sw","descripcion_tarea":"sss","estado":"1"}
INFO - 2024-05-28 21:32:40 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"ss","estado":"1"}
INFO - 2024-05-28 21:32:40 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"ss","estado":"1"}
INFO - 2024-05-28 21:32:43 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"s","estado":"1"}
INFO - 2024-05-28 21:32:43 --> Datos recibidos para guardar tarea: {"nombre_tarea":"sss","descripcion_tarea":"s","estado":"1"}
INFO - 2024-05-28 21:32:47 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":"1"}
INFO - 2024-05-28 21:32:47 --> Datos recibidos para guardar tarea: {"nombre_tarea":"ss","descripcion_tarea":"sss","estado":"1"}
INFO - 2024-05-28 21:33:42 --> Datos recibidos para actualizar estado de la tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:42 --> Datos recibidos para actualizar tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:42 --> Datos recibidos para actualizar estado de la tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:42 --> Datos recibidos para actualizar tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:46 --> Datos recibidos para actualizar estado de la tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:46 --> Datos recibidos para actualizar tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:46 --> Datos recibidos para actualizar estado de la tarea: {"estado":"2"}
INFO - 2024-05-28 21:33:46 --> Datos recibidos para actualizar tarea: {"estado":"2"}
INFO - 2024-05-28 21:53:53 --> Datos recibidos para guardar tarea: {"nombre_tarea":"hvhvhv","descripcion_tarea":"ss","estado":"0"}
INFO - 2024-05-28 21:53:53 --> Datos recibidos para guardar tarea: {"nombre_tarea":"hvhvhv","descripcion_tarea":"ss","estado":"0"}
CRITICAL - 2024-05-28 21:57:54 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: GET, Route: tareas]
in SYSTEMPATH/Database/BaseConnection.php on line 913.
 1 SYSTEMPATH/Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH/Model.php(262): CodeIgniter\Model->builder()
 3 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH/Controllers/TareasController.php(27): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->index()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 21:57:54 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Database\Exceptions\DatabaseException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
You must set the database table to be used with your query.
#0 /Users/unaibueno/Desktop/Mond/system/Model.php(705): CodeIgniter\Database\BaseConnection->table(NULL)
#1 /Users/unaibueno/Desktop/Mond/system/Model.php(262): CodeIgniter\Model->builder()
#2 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#3 /Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php(27): CodeIgniter\BaseModel->findAll()
#4 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->index()
#5 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#6 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#11 {main}
[Method: GET, Route: tareas]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-28 22:12:20 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: GET, Route: tareas]
in SYSTEMPATH/Database/BaseConnection.php on line 913.
 1 SYSTEMPATH/Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH/Model.php(262): CodeIgniter\Model->builder()
 3 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH/Controllers/TareasController.php(27): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->index()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 22:12:20 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Database\Exceptions\DatabaseException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
You must set the database table to be used with your query.
#0 /Users/unaibueno/Desktop/Mond/system/Model.php(705): CodeIgniter\Database\BaseConnection->table(NULL)
#1 /Users/unaibueno/Desktop/Mond/system/Model.php(262): CodeIgniter\Model->builder()
#2 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#3 /Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php(27): CodeIgniter\BaseModel->findAll()
#4 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->index()
#5 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#6 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#11 {main}
[Method: GET, Route: tareas]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-28 22:12:34 --> Error: Call to a member function findAll() on null
[Method: GET, Route: tareas]
in APPPATH/Controllers/TareasController.php on line 26.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->index()
 2 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 3 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 22:12:34 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to a member function findAll() on null
#0 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->index()
#1 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#2 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#4 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#5 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#6 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#7 {main}
[Method: GET, Route: tareas]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-28 22:12:43 --> ErrorException: Undefined property: App\Controllers\TareasController::$ProyectosModel
[Method: GET, Route: tareas]
in APPPATH/Controllers/TareasController.php on line 23.
 1 APPPATH/Controllers/TareasController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\TareasController::$ProyectosModel', '/Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php', 23)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\TareasController->index()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-28 22:12:43 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: App\Controllers\TareasController::$ProyectosModel
#0 /Users/unaibueno/Desktop/Mond/app/Controllers/TareasController.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', '/Users/unaibuen...', 23)
#1 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\TareasController->index()
#2 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TareasController))
#3 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#5 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#6 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#7 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#8 {main}
[Method: GET, Route: tareas]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2024-05-28 22:13:30 --> Datos recibidos para guardar tarea: {"nombre_tarea":"Tarea 1","descripcion_tarea":"esto es una nueva tarea","estado":"0"}
INFO - 2024-05-28 22:13:30 --> Datos recibidos para guardar tarea: {"nombre_tarea":"Tarea 1","descripcion_tarea":"esto es una nueva tarea","estado":"0"}
INFO - 2024-05-28 22:13:33 --> ID de la tarea recibido para eliminar: 10
INFO - 2024-05-28 22:13:33 --> ID de la tarea recibido para eliminar: 10
INFO - 2024-05-28 22:13:33 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:13:36 --> ID de la tarea recibido para eliminar: 6
INFO - 2024-05-28 22:13:36 --> ID de la tarea recibido para eliminar: 6
INFO - 2024-05-28 22:13:36 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:13:38 --> ID de la tarea recibido para eliminar: 8
INFO - 2024-05-28 22:13:38 --> ID de la tarea recibido para eliminar: 8
INFO - 2024-05-28 22:13:39 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:14:38 --> ID de la tarea recibido para eliminar: 4
INFO - 2024-05-28 22:14:38 --> ID de la tarea recibido para eliminar: 4
INFO - 2024-05-28 22:14:38 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:14:40 --> ID de la tarea recibido para eliminar: 9
INFO - 2024-05-28 22:14:40 --> ID de la tarea recibido para eliminar: 9
INFO - 2024-05-28 22:14:40 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:14:41 --> ID de la tarea recibido para eliminar: 5
INFO - 2024-05-28 22:14:41 --> ID de la tarea recibido para eliminar: 5
INFO - 2024-05-28 22:14:41 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:14:43 --> ID de la tarea recibido para eliminar: 1
INFO - 2024-05-28 22:14:43 --> ID de la tarea recibido para eliminar: 1
INFO - 2024-05-28 22:14:43 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:14:44 --> ID de la tarea recibido para eliminar: 7
INFO - 2024-05-28 22:14:44 --> ID de la tarea recibido para eliminar: 7
INFO - 2024-05-28 22:14:45 --> Tarea eliminada correctamente
INFO - 2024-05-28 22:15:04 --> Datos recibidos para guardar tarea: {"nombre_tarea":"Tarea 2","descripcion_tarea":"Esto es una tarea","estado":"0"}
INFO - 2024-05-28 22:15:04 --> Datos recibidos para guardar tarea: {"nombre_tarea":"Tarea 2","descripcion_tarea":"Esto es una tarea","estado":"0"}
