CRITICAL - 2024-05-23 17:03:01 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "@fortawesome"
[Method: GET, Route: vendor/@fortawesome/fontawesome-free/css/all.min.css]
in SYSTEMPATH/Router/Router.php on line 736.
 1 SYSTEMPATH/Router/Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 2 SYSTEMPATH/CodeIgniter.php(834): CodeIgniter\Router\Router->handle('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 3 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 17:03:02 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "@fortawesome"
[Method: GET, Route: vendor/@fortawesome/fontawesome-free/css/all.min.css]
in SYSTEMPATH/Router/Router.php on line 736.
 1 SYSTEMPATH/Router/Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 2 SYSTEMPATH/CodeIgniter.php(834): CodeIgniter\Router\Router->handle('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 3 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
ERROR - 2024-05-23 17:59:11 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 17:59:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 17:59:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-04-30\', \'2024-05-15\', \'2024-05-23 17:59:11\', \'2024-05-23 17:59:11\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-04-30\', \'2024-05-15\', \'2024-05-23 17:59:11\', \'2024-05-23 17:59:11\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 17:59:11 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-04-30\', \'2024-05-15\', \'2024-05-23 17:59:11\', \'2024-05-23 17:59:11\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-04-30\', \'2024-05-15\', \'2024-05-23 17:59:11\', \'2024-05-23 17:59:11\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-04-30\', \'2024-05-15\', \'2024-05-23 17:59:11\', \'2024-05-23 17:59:11\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
ERROR - 2024-05-23 17:59:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 17:59:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 17:59:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 17:59:19\', \'2024-05-23 17:59:19\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 17:59:19\', \'2024-05-23 17:59:19\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 17:59:19 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 17:59:19\', \'2024-05-23 17:59:19\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 17:59:19\', \'2024-05-23 17:59:19\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 17:59:19\', \'2024-05-23 17:59:19\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
ERROR - 2024-05-23 18:00:20 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:00:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:00:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-07\', \'2024-05-29\', \'2024-05-23 18:00:20\', \'2024-05-23 18:00:20\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-07\', \'2024-05-29\', \'2024-05-23 18:00:20\', \'2024-05-23 18:00:20\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:00:20 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-07\', \'2024-05-29\', \'2024-05-23 18:00:20\', \'2024-05-23 18:00:20\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-07\', \'2024-05-29\', \'2024-05-23 18:00:20\', \'2024-05-23 18:00:20\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-07\', \'2024-05-29\', \'2024-05-23 18:00:20\', \'2024-05-23 18:00:20\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
ERROR - 2024-05-23 18:01:05 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:01:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:01:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-14\', \'2024-05-22\', \'2024-05-23 18:01:05\', \'2024-05-23 18:01:05\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-14\', \'2024-05-22\', \'2024-05-23 18:01:05\', \'2024-05-23 18:01:05\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:01:05 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-14\', \'2024-05-22\', \'2024-05-23 18:01:05\', \'2024-05-23 18:01:05\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-14\', \'2024-05-22\', \'2024-05-23 18:01:05\', \'2024-05-23 18:01:05\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'ss\', \'s\', \'2024-05-14\', \'2024-05-22\', \'2024-05-23 18:01:05\', \'2024-05-23 18:01:05\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:01:45 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "@fortawesome"
[Method: GET, Route: vendor/@fortawesome/fontawesome-free/css/all.min.css]
in SYSTEMPATH/Router/Router.php on line 736.
 1 SYSTEMPATH/Router/Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 2 SYSTEMPATH/CodeIgniter.php(834): CodeIgniter\Router\Router->handle('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 3 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
ERROR - 2024-05-23 18:02:01 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:02:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:02:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 18:02:01\', \'2024-05-23 18:02:01\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 18:02:01\', \'2024-05-23 18:02:01\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:02:01 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 18:02:01\', \'2024-05-23 18:02:01\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 18:02:01\', \'2024-05-23 18:02:01\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-22\', \'2024-05-23 18:02:01\', \'2024-05-23 18:02:01\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 18:03:14 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-07","fecha_fin":"2024-05-16"}
ERROR - 2024-05-23 18:03:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:03:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:03:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-16\', \'2024-05-23 18:03:14\', \'2024-05-23 18:03:14\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-16\', \'2024-05-23 18:03:14\', \'2024-05-23 18:03:14\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:03:14 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-16\', \'2024-05-23 18:03:14\', \'2024-05-23 18:03:14\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-16\', \'2024-05-23 18:03:14\', \'2024-05-23 18:03:14\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-07\', \'2024-05-16\', \'2024-05-23 18:03:14\', \'2024-05-23 18:03:14\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 18:03:23 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-21","fecha_fin":"2024-06-05"}
ERROR - 2024-05-23 18:03:23 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:03:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:03:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-21\', \'2024-06-05\', \'2024-05-23 18:03:23\', \'2024-05-23 18:03:23\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-21\', \'2024-06-05\', \'2024-05-23 18:03:23\', \'2024-05-23 18:03:23\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:03:23 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-21\', \'2024-06-05\', \'2024-05-23 18:03:23\', \'2024-05-23 18:03:23\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-21\', \'2024-06-05\', \'2024-05-23 18:03:23\', \'2024-05-23 18:03:23\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-21\', \'2024-06-05\', \'2024-05-23 18:03:23\', \'2024-05-23 18:03:23\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 18:04:18 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-14","fecha_fin":"2024-05-23"}
ERROR - 2024-05-23 18:04:18 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 /Users/unaibueno/Desktop/Mond/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 /Users/unaibueno/Desktop/Mond/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 /Users/unaibueno/Desktop/Mond/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Users/unaibueno/Desktop/Mond/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/unaibueno/Desktop/Mond/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save(Array)
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
#10 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
#11 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#16 {main}
CRITICAL - 2024-05-23 18:04:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: save-event]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:04:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-14\', \'2024-05-23\', \'2024-05-23 18:04:18\', \'2024-05-23 18:04:18\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-14\', \'2024-05-23\', \'2024-05-23 18:04:18\', \'2024-05-23 18:04:18\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:04:18 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-14\', \'2024-05-23\', \'2024-05-23 18:04:18\', \'2024-05-23 18:04:18\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-14\', \'2024-05-23\', \'2024-05-23 18:04:18\', \'2024-05-23 18:04:18\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (\'s\', \'s\', \'2024-05-14\', \'2024-05-23\', \'2024-05-23 18:04:18\', \'2024-05-23 18:04:18\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `calendario` (`titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `created_at`, `updated_at`) VALUES (:titulo:, :descripcion:, :fecha_inicio:, :fecha_fin:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/CalendarioController.php(36): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->saveEvent()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 18:05:53 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-08","fecha_fin":"2024-05-16"}
INFO - 2024-05-23 18:07:53 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-07","fecha_fin":"2024-05-15"}
INFO - 2024-05-23 18:07:56 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-14","fecha_fin":"2024-05-15"}
INFO - 2024-05-23 18:07:59 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-09","fecha_fin":"2024-05-10"}
INFO - 2024-05-23 18:08:50 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-06","fecha_fin":"2024-05-15"}
INFO - 2024-05-23 18:09:04 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-23T07:30:00+02:00","fecha_fin":"2024-05-23T10:00:00+02:00"}
CRITICAL - 2024-05-23 18:24:09 --> Error: Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
[Method: GET, Route: calendario]
in APPPATH/Controllers/CalendarioController.php on line 1.
 1 SYSTEMPATH/Autoloader/Autoloader.php(317): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php')
 3 SYSTEMPATH/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\CalendarioController')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\CalendarioController')
 5 SYSTEMPATH/CodeIgniter.php(887): class_exists('\\App\\Controllers\\CalendarioController', true)
 6 SYSTEMPATH/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:24:10 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
#0 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(317): include_once()
#1 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibuen...')
#2 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#4 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(887): class_exists('\\App\\Controller...', true)
#5 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
#6 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#11 {main}
[Method: GET, Route: calendario]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-23 18:25:28 --> Error: Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
[Method: GET, Route: calendario]
in APPPATH/Controllers/CalendarioController.php on line 1.
 1 SYSTEMPATH/Autoloader/Autoloader.php(317): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php')
 3 SYSTEMPATH/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\CalendarioController')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\CalendarioController')
 5 SYSTEMPATH/CodeIgniter.php(887): class_exists('\\App\\Controllers\\CalendarioController', true)
 6 SYSTEMPATH/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:25:28 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
#0 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(317): include_once()
#1 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibuen...')
#2 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#4 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(887): class_exists('\\App\\Controller...', true)
#5 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
#6 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#11 {main}
[Method: GET, Route: calendario]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-23 18:26:08 --> Error: Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
[Method: GET, Route: calendario]
in APPPATH/Controllers/CalendarioController.php on line 1.
 1 SYSTEMPATH/Autoloader/Autoloader.php(317): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibueno/Desktop/Mond/app/Controllers/CalendarioController.php')
 3 SYSTEMPATH/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\CalendarioController')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\CalendarioController')
 5 SYSTEMPATH/CodeIgniter.php(887): class_exists('\\App\\Controllers\\CalendarioController', true)
 6 SYSTEMPATH/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-23 18:26:08 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined method CodeIgniter\Autoloader\Autoloader::extend()
#0 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(317): include_once()
#1 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/unaibuen...')
#2 /Users/unaibueno/Desktop/Mond/system/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#4 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(887): class_exists('\\App\\Controller...', true)
#5 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
#6 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /Users/unaibueno/Desktop/Mond/public/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#11 {main}
[Method: GET, Route: calendario]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2024-05-23 18:27:03 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"sssssss","fecha_inicio":"2024-05-17","fecha_fin":"2024-05-19"}
INFO - 2024-05-23 18:39:14 --> Datos recibidos para guardar evento: {"titulo":"m","descripcion":"n","fecha_inicio":"2024-05-20T07:00:00+02:00","fecha_fin":"2024-05-20T10:00:00+02:00"}
INFO - 2024-05-23 19:06:46 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:06:50 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:06:54 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:07:01 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:07:20 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"ss","fecha_inicio":"2024-05-29","fecha_fin":"2024-05-30"}
INFO - 2024-05-23 19:07:20 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"ss","fecha_inicio":"2024-05-29","fecha_fin":"2024-05-30"}
INFO - 2024-05-23 19:08:10 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-07","fecha_fin":"2024-05-08"}
INFO - 2024-05-23 19:08:10 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-07","fecha_fin":"2024-05-08"}
INFO - 2024-05-23 19:09:11 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:10:42 --> ID del evento recibido para eliminar: null
INFO - 2024-05-23 19:10:42 --> ID del evento recibido para eliminar: 
INFO - 2024-05-23 19:12:46 --> ID del evento recibido para eliminar: null
INFO - 2024-05-23 19:12:46 --> ID del evento recibido para eliminar: 
CRITICAL - 2024-05-23 19:12:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: delete-event]
in SYSTEMPATH/Database/BaseBuilder.php on line 2794.
 1 SYSTEMPATH/Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH/BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 3 APPPATH/Models/CalendarioModel.php(53): CodeIgniter\BaseModel->delete(null)
 4 APPPATH/Controllers/CalendarioController.php(64): App\Models\CalendarioModel->deleteEvent(null)
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->deleteEvent()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 19:13:07 --> ID del evento recibido para eliminar: null
INFO - 2024-05-23 19:13:07 --> ID del evento recibido para eliminar: 
CRITICAL - 2024-05-23 19:13:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: delete-event]
in SYSTEMPATH/Database/BaseBuilder.php on line 2794.
 1 SYSTEMPATH/Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH/BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 3 APPPATH/Models/CalendarioModel.php(53): CodeIgniter\BaseModel->delete(null)
 4 APPPATH/Controllers/CalendarioController.php(64): App\Models\CalendarioModel->deleteEvent(null)
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->deleteEvent()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 19:14:43 --> ID del evento recibido para eliminar: null
INFO - 2024-05-23 19:14:43 --> ID del evento recibido para eliminar: 
CRITICAL - 2024-05-23 19:14:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: delete-event]
in SYSTEMPATH/Database/BaseBuilder.php on line 2794.
 1 SYSTEMPATH/Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH/BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 3 APPPATH/Models/CalendarioModel.php(53): CodeIgniter\BaseModel->delete(null)
 4 APPPATH/Controllers/CalendarioController.php(64): App\Models\CalendarioModel->deleteEvent(null)
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->deleteEvent()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 19:16:00 --> ID del evento recibido para eliminar: null
INFO - 2024-05-23 19:16:00 --> ID del evento recibido para eliminar: 
CRITICAL - 2024-05-23 19:16:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: delete-event]
in SYSTEMPATH/Database/BaseBuilder.php on line 2794.
 1 SYSTEMPATH/Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH/BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 3 APPPATH/Models/CalendarioModel.php(53): CodeIgniter\BaseModel->delete(null)
 4 APPPATH/Controllers/CalendarioController.php(64): App\Models\CalendarioModel->deleteEvent(null)
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CalendarioController->deleteEvent()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CalendarioController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
INFO - 2024-05-23 19:19:31 --> ID del evento recibido para eliminar: 10
INFO - 2024-05-23 19:19:38 --> Datos recibidos para guardar evento: {"titulo":"sss","descripcion":"sccscxsc","fecha_inicio":"2024-05-07","fecha_fin":"2024-05-16"}
INFO - 2024-05-23 19:19:44 --> ID del evento recibido para eliminar: 11
INFO - 2024-05-23 19:19:51 --> Datos recibidos para guardar evento: {"titulo":"ssac","descripcion":"xcaxccxc","fecha_inicio":"2024-04-30","fecha_fin":"2024-05-08"}
INFO - 2024-05-23 19:31:37 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-08","fecha_fin":"2024-05-09"}
INFO - 2024-05-23 19:33:27 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-09","fecha_fin":"2024-05-11"}
INFO - 2024-05-23 19:35:06 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"","fecha_inicio":"2024-05-14","fecha_fin":"2024-05-23"}
INFO - 2024-05-23 19:48:30 --> Datos recibidos para guardar evento: {"titulo":"s","descripcion":"s","fecha_inicio":"2024-05-23","fecha_fin":"2024-05-24"}
INFO - 2024-05-23 19:53:37 --> ID del evento recibido para eliminar: 15
INFO - 2024-05-23 19:53:41 --> ID del evento recibido para eliminar: 16
INFO - 2024-05-23 20:21:15 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"s","fecha_inicio":"2024-05-15","fecha_fin":"2024-05-17"}
INFO - 2024-05-23 20:21:46 --> ID del evento recibido para eliminar: 12
INFO - 2024-05-23 20:21:51 --> ID del evento recibido para eliminar: 14
INFO - 2024-05-23 20:21:58 --> ID del evento recibido para eliminar: 17
INFO - 2024-05-23 20:34:27 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"s","fecha_inicio":"2024-05-16","fecha_fin":"2024-05-17"}
INFO - 2024-05-23 20:34:32 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"s","fecha_inicio":"2024-05-24","fecha_fin":"2024-05-26"}
INFO - 2024-05-23 20:34:37 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"s","fecha_inicio":"2024-05-20","fecha_fin":"2024-05-30"}
INFO - 2024-05-23 20:34:43 --> ID del evento recibido para eliminar: 20
INFO - 2024-05-23 20:35:08 --> Datos recibidos para guardar evento: {"titulo":"ss","descripcion":"sss","fecha_inicio":"2024-05-20","fecha_fin":"2024-05-22"}
