CRITICAL - 2024-05-10 16:32:38 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 59.
 1 APPPATH/Views/dashboard/index.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 59)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:33:45 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 59.
 1 APPPATH/Views/dashboard/index.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 59)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:34:00 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 59.
 1 APPPATH/Views/dashboard/index.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 59)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:34:00 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 59.
 1 APPPATH/Views/dashboard/index.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 59)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:34:45 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/master/master.php on line 252.
 1 APPPATH/Views/master/master.php(252): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/master/master.php', 252)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/master/master.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/View/View.php(250): CodeIgniter\View\View->render('master/master', [], true)
 5 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 6 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:34:46 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/master/master.php on line 252.
 1 APPPATH/Views/master/master.php(252): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/master/master.php', 252)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/master/master.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/View/View.php(250): CodeIgniter\View\View->render('master/master', [], true)
 5 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 6 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:35:23 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Controllers/Dashboard.php on line 23.
 1 APPPATH/Controllers/Dashboard.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php', 23)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:35:36 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Controllers/Dashboard.php on line 23.
 1 APPPATH/Controllers/Dashboard.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php', 23)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:35:36 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Controllers/Dashboard.php on line 23.
 1 APPPATH/Controllers/Dashboard.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php', 23)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:35:37 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Controllers/Dashboard.php on line 23.
 1 APPPATH/Controllers/Dashboard.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php', 23)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:37:15 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 51.
 1 APPPATH/Views/dashboard/index.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 51)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:37:28 --> ErrorException: Undefined variable $data
[Method: GET, Route: dashboard]
in APPPATH/Views/dashboard/index.php on line 51.
 1 APPPATH/Views/dashboard/index.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', '/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php', 51)
 2 SYSTEMPATH/View/View.php(234): include('/Users/unaibueno/Desktop/Mond/app/Views/dashboard/index.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('dashboard/index', [], true)
 5 APPPATH/Controllers/Dashboard.php(26): view('dashboard/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:42:54 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:42:54 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:43:30 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:43:30 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:44:03 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:44:03 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:44:10 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:44:10 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:44:26 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:44:26 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:44:27 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:44:27 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:45:04 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:45:04 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:45:32 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:45:32 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:45:33 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:45:33 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:46:02 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:46:02 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:46:02 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:46:02 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 16:46:02 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 16:46:02 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 17:36:40 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 17:36:40 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 17:36:41 --> Error: Class "CodeIgniter\Database\MySQL\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 17:36:41 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\MySQL\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 17:37:04 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "@fortawesome"
[Method: GET, Route: vendor/@fortawesome/fontawesome-free/css/all.min.css]
in SYSTEMPATH/Router/Router.php on line 736.
 1 SYSTEMPATH/Router/Router.php(203): CodeIgniter\Router\Router->checkDisallowedChars('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 2 SYSTEMPATH/CodeIgniter.php(834): CodeIgniter\Router\Router->handle('vendor/@fortawesome/fontawesome-free/css/all.min.css')
 3 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 17:59:03 --> Error: Class "CodeIgniter\Database\mysql\Connection" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH/Database/Database.php on line 139.
 1 SYSTEMPATH/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', [...])
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(235): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\TareasModel', [...])
 6 SYSTEMPATH/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 APPPATH/Controllers/Dashboard.php(11): model('TareasModel')
 8 SYSTEMPATH/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
 9 SYSTEMPATH/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Users/unaibueno/Desktop/Mond/public/index.php')
CRITICAL - 2024-05-10 17:59:03 --> ErrorException: Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in /Users/unaibueno/Desktop/Mond/app/Views/errors/html/error_exception.php:33
Stack trace:
#0 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(266): include()
#1 /Users/unaibueno/Desktop/Mond/system/Debug/BaseExceptionHandler.php(269): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 /Users/unaibueno/Desktop/Mond/system/Debug/ExceptionHandler.php(114): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, '/Users/unaibuen...')
#3 /Users/unaibueno/Desktop/Mond/system/Debug/Exceptions.php(163): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "CodeIgniter\Database\mysql\Connection" not found
#0 /Users/unaibueno/Desktop/Mond/system/Database/Database.php(57): CodeIgniter\Database\Database->initDriver('mysql', 'Connection', Array)
#1 /Users/unaibueno/Desktop/Mond/system/Database/Config.php(84): CodeIgniter\Database\Database->load(Array, 'default')
#2 /Users/unaibueno/Desktop/Mond/system/Model.php(155): CodeIgniter\Database\Config::connect('default')
#3 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(235): CodeIgniter\Model->__construct(NULL)
#4 /Users/unaibueno/Desktop/Mond/system/Config/Factories.php(169): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\Tare...', Array)
#5 /Users/unaibueno/Desktop/Mond/system/Common.php(802): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 /Users/unaibueno/Desktop/Mond/app/Controllers/Dashboard.php(11): model('TareasModel')
#7 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(903): App\Controllers\Dashboard->__construct()
#8 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
#9 /Users/unaibueno/Desktop/Mond/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/unaibueno/Desktop/Mond/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 /Users/unaibueno/Desktop/Mond/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Users/unaibueno/Desktop/Mond/public/index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Users/unaibueno/Desktop/Mond/system/Commands/Server/rewrite.php(49): require_once('/Users/unaibuen...')
#14 {main}
[Method: GET, Route: dashboard]
in APPPATH/Views/errors/html/error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
